### ISSUE TITLE
백오피스

### ISSUE THREAD

**Issue by ydh5017** [nbcamp-FC/codeplanet#19]
## Description
백오피스 기능 구현

## To-do
- [x] Company 추가 메서드 기능 구현
- [ ] User 전체 목록 조회 기능 구현
- [x] User 권한 수정 기능 구현
- [ ] Feed, Reply 전체 조회 기능 구현
- [ ] Feed, Reply 전체 수정, 삭제 기능 구현

## ETC
기타사항 없음
